import numpy as np
NumberOfAnts = 2
MaxActiveDropletsPerAnt = 300
Pi = 3.1415926535
seed1 = 1
t_hat_in_seconds = 1.0
X_hat_in_cm = 1.0
tau = 0.1
TAU = tau / t_hat_in_seconds
SensingAreaRadius = 1.0
SENSING_AREA_RADIUS = SensingAreaRadius / X_hat_in_cm
SensingAreaHalfAnglePiOver = 4.0
SensingAreaHalfAngle = np.pi/SensingAreaHalfAnglePiOver
NaturalVelocityIncmsec = 3.5
NaturalVelocity = NaturalVelocityIncmsec * t_hat_in_seconds / X_hat_in_cm
delta_t = 0.1
Diffusion = 0.003
Evaporation = 0.0001
DropletAmountPerUnitTime = 10.0
DropletAmount = DropletAmountPerUnitTime * delta_t
Threshold = 0.2
LambdaDeltas = NaturalVelocity/(SENSING_AREA_RADIUS*np.cos(SensingAreaHalfAngle))
LambdaNonlocal = (3./2.)*NaturalVelocity*SensingAreaHalfAngle/(SENSING_AREA_RADIUS*np.sin(SensingAreaHalfAngle))
Lambda = 1.0
x_1_cm = -10
x_2_cm = 10
y_1_cm = -10
y_2_cm = 10
x_1 = x_1_cm / X_hat_in_cm
x_2 = x_2_cm / X_hat_in_cm
y_1 = y_1_cm / X_hat_in_cm
y_2 = y_2_cm / X_hat_in_cm
