import numpy as np
NumberOfAnts = 60
MaxActiveDropletsPerAnt = 80
Cores = 4
seed1 = 1
t_hat_in_seconds = 1.0
X_hat_in_cm = 1.0
tau = 0.1
TAU = tau / t_hat_in_seconds
SensingAreaRadius = 0.4
SENSING_AREA_RADIUS = SensingAreaRadius /X_hat_in_cm
SensingAreaHalfAnglePiOver = 4.0
SensingAreaHalfAngle = np.pi/SensingAreaHalfAnglePiOver
NaturalVelocityIncmsec = 2.
NaturalVelocity = NaturalVelocityIncmsec * t_hat_in_seconds / X_hat_in_cm
delta_t = 0.06
Diffusion = 0.3
Evaporation = 0.01
DropletAmountPerUnitTime = 100.0
drop_every_seconds = 1.0
drop_every_t_hat = drop_every_seconds / t_hat_in_seconds
DropletAmount = DropletAmountPerUnitTime * drop_every_t_hat
Threshold = 0.2
LambdaDeltas = NaturalVelocity/(SENSING_AREA_RADIUS*np.cos(SensingAreaHalfAngle))
x_1_cm = -20
x_2_cm = 20
y_1_cm = -20
y_2_cm = 20
x_1 = x_1_cm / X_hat_in_cm
x_2 = x_2_cm / X_hat_in_cm
y_1 = y_1_cm / X_hat_in_cm
y_2 = y_2_cm / X_hat_in_cm
