import numpy as np
NumberOfAnts = 50
MaxActiveDropletsPerAnt = 150
Cores = 1
seed1 = 2
t_hat_in_seconds = 1.0
X_hat_in_cm = 1.0
tau = 0.1
TAU = tau / t_hat_in_seconds
SensingAreaRadius = 1.0
SENSING_AREA_RADIUS = SensingAreaRadius /X_hat_in_cm
SensingAreaHalfAnglePiOver = 4.0
SensingAreaHalfAngle = np.pi/SensingAreaHalfAnglePiOver
NaturalVelocityIncmsec = 3.5
NaturalVelocity = NaturalVelocityIncmsec * t_hat_in_seconds / X_hat_in_cm
delta_t = 0.1
Diffusion = 0.003
Evaporation = 0.0001
DropletAmountPerUnitTime = 10.0
drop_every_seconds = 0.5
drop_every_t_hat = drop_every_seconds / t_hat_in_seconds
DropletAmount = DropletAmountPerUnitTime * drop_every_t_hat
Threshold = 0.2
LambdaDeltas = NaturalVelocity/(SENSING_AREA_RADIUS*np.cos(SensingAreaHalfAngle))
x_1_cm = -50
x_2_cm = 50
y_1_cm = -50
y_2_cm = 50
x_1 = x_1_cm / X_hat_in_cm
x_2 = x_2_cm / X_hat_in_cm
y_1 = y_1_cm / X_hat_in_cm
y_2 = y_2_cm / X_hat_in_cm
BC = 'reflective'
